export const ADD_STATUS = 'PERSONNELS_PAGE/SINGLE/ADD_STATUS';
export const ADD_STATUS_SUCCESS = 'PERSONNELS_PAGE/SINGLE/ADD_STATUS_SUCCESS';
export const ADD_STATUS_FAILURE = 'PERSONNELS_PAGE/SINGLE/ADD_STATUS_FAILURE';

export const DELETE_STATUS = 'PERSONNELS_PAGE/SINGLE/DELETE_STATUS';
export const DELETE_STATUS_SUCCESS =
  'PERSONNELS_PAGE/SINGLE/DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAILURE =
  'PERSONNELS_PAGE/SINGLE/DELETE_STATUS_FAILURE';
