export const UPDATE_EVENT = 'EVENTS/EDIT/UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'EVENTS/EDIT/UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'EVENTS/EDIT/UPDATE_EVENT_FAILURE';
export const UPDATE_EVENT_NO_CHANGE = 'PERSONNELS/EDIT/UPDATE_EVENT_NO_CHANGE';
