export const UPDATE_PERSON = 'PERSONNELS/EDIT/UPDATE_PERSON';
export const UPDATE_PERSON_SUCCESS = 'PERSONNELS/EDIT/UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'PERSONNELS/EDIT/UPDATE_PERSON_FAILURE';
