export const DELETE_PERSONNEL = 'PERSONNELS_PAGE/ALL/DELETE_PERSONNEL';
export const DELETE_PERSONNEL_SUCCESS =
  'PERSONNELS_PAGE/ALL/DELETE_PERSONNEL_SUCCESS';
export const DELETE_PERSONNEL_FAILURE =
  'PERSONNELS_PAGE/ALL/DELETE_PERSONNEL_FAILURE';
export const CLEAR_ERROR_MESSAGE = 'PERSONNELS_PAGE/ALL/CLEAR_ERROR_MESSAGE';
